# This file contains values from Cookiecutter

default_context:
  project_name: "horiba-python-sdk"
  project_description: "'horiba-python-sdk' is a package that provides source code for the development with Horiba devices"
  organization: "ZühlkeEngineering"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "ThatsTheEnd"
  email: "nikolaus.naredi-rainer@zuehlke.com"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
